#define DLL_PROCESS_DETACH 0
#define DLL_PROCESS_ATTACH 1

#define IMAGE_REL_BASED_HIGH 1
#define IMAGE_REL_BASED_LOW 2
#define IMAGE_REL_BASED_HIGHLOW 3

#define MEM_RELEASE 0x8000

#define ERROR_FILE_NOT_FOUND 2
#define ERROR_INVALID_HANDLE 6
#define ERROR_NO_MORE_FILES 18
#define ERROR_INVALID_PARAMETER 87
#define ERROR_SEEK_ON_DEVICE 0x84

#define TLS_OUT_OF_INDEXES 0xffffffff

#define REG_SZ  0x00000001
#define REG_DWORD  0x00000004
#define ERROR_MORE_DATA 234
#define MMSYSERR_NODRIVER 6

#define CREATE_ALWAYS 2
#define CREATE_NEW 1
#define OPEN_ALWAYS 4
#define OPEN_EXISTING 3
#define TRUNCATE_EXISTING 5
#define GENERIC_WRITE 0x40000000
#define GENERIC_READ 0x80000000

#define INVALID_FILE_SIZE 0xFFFFFFFF
#define INVALID_HANDLE_VALUE ((HANDLE)-1)
