#include <stdint.h>
//typedef uint32_t DWORD;
//typedef uint16_t WORD;
typedef int32_t BOOL;
typedef int32_t HRESULT;
//typedef uintptr_t HANDLE;
typedef HANDLE HWND;
typedef HANDLE HMENU;
typedef HANDLE HHOOK;
typedef HANDLE HICON;
typedef HANDLE HBITMAP;
typedef HANDLE HDC;
typedef HANDLE HGDIOBJ;
typedef uint16_t WCHAR;
typedef char *PSTR;
typedef WCHAR *PWSTR;
typedef struct MSG MSG;
typedef struct {
	uint16_t wYear, wMonth, wDayOfWeek, wDay, wHour, wMinute, wSecond, wMilliseconds;
} SYSTEMTIME;
typedef struct BITMAPINFO BITMAPINFO;
typedef struct {
	int32_t x, y;
} POINT;
typedef struct RECT RECT;
typedef struct DEVMODEA DEVMODEA;
typedef struct STARTUPINFOA STARTUPINFOA;
typedef struct WNDCLASSA WNDCLASSA;
typedef struct IUnknown IUnknown;
typedef struct SOCKADDR SOCKADDR;

typedef int32_t CDS_TYPE;
typedef int32_t CLSCTX;
typedef int32_t COMM_EVENT_MASK;
typedef int32_t COMMTIMEOUTS;
typedef int32_t CreatedHDC;
typedef int32_t DCB;
typedef int32_t DIB_USAGE;
typedef int32_t DISP_CHANGE;
typedef int32_t ENUM_DISPLAY_SETTINGS_MODE;
typedef int32_t ESCAPE_COMM_FUNCTION;
typedef int32_t FILE_ACCESS_FLAGS;
typedef int32_t FILE_CREATION_DISPOSITION;
typedef int32_t FILE_FLAGS_AND_ATTRIBUTES;
typedef int32_t FILE_MAP;
typedef int32_t FILE_SHARE_MODE;
typedef int32_t FindFileHandle;
typedef int32_t GET_DEVICE_CAPS_INDEX;
typedef int32_t GET_STOCK_OBJECT_FLAGS;
typedef int32_t GLOBAL_ALLOC_FLAGS;
typedef int32_t Guid;
typedef int32_t HEAP_FLAGS;
typedef int32_t HeapHandle;
typedef void *HOOKPROC;
typedef int32_t IDirectDraw;
typedef int32_t JOYINFOEX;
typedef int32_t LPDDENUMCALLBACKA;
typedef int32_t LPTHREAD_START_ROUTINE;
typedef int32_t LPTOP_LEVEL_EXCEPTION_FILTER;
typedef int32_t LSTATUS;
typedef struct {
	uint32_t dwLength, dwMemoryLoad;
	uint32_t dwTotalPhys, dwAvailPhys, dwTotalPageFile, dwAvailPageFile, dwTotalVirtual, dwAvailVirtual;
} MEMORYSTATUS;
typedef int32_t MENU_ITEM_FLAGS;
typedef int32_t MESSAGEBOX_RESULT;
typedef int32_t MESSAGEBOX_STYLE;
typedef int32_t OVERLAPPED;
typedef int32_t PAGE_PROTECTION_FLAGS;
typedef int32_t PAINTSTRUCT;
typedef int32_t PEEK_MESSAGE_REMOVE_TYPE;
typedef int32_t PIXELFORMATDESCRIPTOR;
typedef int32_t PROCESS_ACCESS_RIGHTS;
typedef int32_t PROCESS_CREATION_FLAGS;
typedef int32_t PURGE_COMM_FLAGS;
typedef int32_t REG_OPEN_CREATE_OPTIONS;
typedef int32_t REG_SAM_FLAGS;
typedef int32_t REG_VALUE_TYPE;
typedef int32_t ROP_CODE;
typedef int32_t SET_WINDOW_POS_FLAGS;
typedef int32_t SHOW_WINDOW_CMD;
typedef int32_t SYSTEM_METRICS_INDEX;
typedef int32_t TEXTMETRICA;
typedef int32_t THREAD_CREATION_FLAGS;
typedef int32_t THREAD_PRIORITY;
typedef struct {
	uint32_t wPeriodMin, wPeriodMax;
} TIMECAPS;
typedef int32_t WINDOW_EX_STYLE;
typedef int32_t WINDOWS_HOOK_ID;
typedef int32_t WINDOW_STYLE;
typedef uint32_t MMRESULT;
typedef uintptr_t SOCKET;
typedef uint32_t IN_ADDR;
typedef struct timeval timeval;
typedef int32_t SEND_FLAGS;

typedef struct _OSVERSIONINFOA {
	uint32_t dwOSVersionInfoSize;
	uint32_t dwMajorVersion;
	uint32_t dwMinorVersion;
	uint32_t dwBuildNumber;
	uint32_t dwPlatformId;
	char  szCSDVersion[128];
} OSVERSIONINFOA;

typedef struct GLYPHMETRICSFLOAT GLYPHMETRICSFLOAT;
typedef struct LAYERPLANEDESCRIPTOR LAYERPLANEDESCRIPTOR;
typedef HANDLE HGLRC;
typedef struct {
	DWORD dwFileAttributes;
	FILETIME ftCreationTime;
	FILETIME ftLastAccessTime;
	FILETIME ftLastWriteTime;
	DWORD nFileSizeHigh;
	DWORD nFileSizeLow;
	DWORD dwReserved0;
	DWORD dwReserved1;
	char cFileName[MAX_PATH];
	char cAlternateFileName[14];
	DWORD dwFileType;
	DWORD dwCreatorType;
	WORD wFinderFlags;
} WIN32_FIND_DATAA;
